# Generated by Django 5.2.1 on 2025-05-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
